# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

svol_leverage_approx_LL <- function(obsTS, params) {
    .Call(`_pfr_svol_leverage_approx_LL`, obsTS, params)
}

svol_leverage_approx_filt <- function(obsTS, params) {
    .Call(`_pfr_svol_leverage_approx_filt`, obsTS, params)
}

