# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib pfr, .registration = TRUE
#' @import RcppEigen
#' @importFrom Rcpp evalCpp
#' @export
svol_leverage_bswc_approx_LL <- function(obsTS, params) {
    .Call('_pfr_svol_leverage_bswc_approx_LL', PACKAGE = 'pfr', obsTS, params)
}

#' @useDynLib pfr, .registration = TRUE
#' @import RcppEigen
#' @importFrom Rcpp evalCpp
#' @export
svol_leverage_bswc_approx_filt <- function(obsTS, params) {
    .Call('_pfr_svol_leverage_bswc_approx_filt', PACKAGE = 'pfr', obsTS, params)
}

